# Generated by Django 3.1 on 2020-08-07 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ahia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='asset_category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
