# Generated by Django 3.0.8 on 2020-08-12 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ahia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='asset_category',
        ),
    ]
