# Generated by Django 3.0.8 on 2020-08-10 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ahia', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
